---
- name: (configure) create completion dir
  file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: (configure) download docker bash completion
  get_url:
    url: "{{ takel_docker_completion_url }}"
    dest: "{{ takel_docker_completion_path }}"
    owner: root
    group: root
    mode: 0644
