---
- name: (playbook-project-prod) create project prod
  hosts: all
  become: true
  roles:
    - takel-base
    - takel-anarchism
    - takel-ufw
    - takel-unattended-upgrades
    - takel-docker
    - takel-cleanup
